on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f src/requirements.txt ]; then pip install -r src/requirements.txt; fi

  deploy-aws:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Criar arquivo application.env
      run: |
        echo "awsRegion=${{ secrets.AWS_REGION }}" >> src/application.env
        echo "userPoolId=${{ secrets.USER_POOL_ID }}" >> src/application.env
        echo "clientId=${{ secrets.CLIENT_ID }}" >> src/application.env
        echo "clientSecret=${{ secrets.CLIENT_SECRET }}" >> src/application.env
        echo "awsClientCognito=cognito-idp" >> src/application.env
        echo "groupNameDefault=${{ secrets.GROUP_NAME_DEFAULT }}" >> src/application.env
        echo "groupNameAdmin=${{ secrets.GROUP_NAME_ADMIN }}" >> src/application.env
        echo "groupsWithAccessPermissions=${{ secrets.GROUPS_WITH_ACCESS_PERMISSIONS }}" >> src/application.env

    - name: Install AWS SAM CLI
      run: |
        pip install aws-sam-cli

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Build SAM application
      run: |
        sam build --no-cached --debug

    - name: Deploy SAM application
      run: |
        sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --capabilities CAPABILITY_IAM